services:
  - type: web
    name: sikham-school
    runtime: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school_db
          property: connectionString
      - key: IMPORT_DB_ON_START
        value: "true"
